"""initial schema

Revision ID: 6c12df2d3498
Revises: 
Create Date: 2026-08-21 01:23:41.822936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c12df2d3498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('creators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creator_type', sa.Enum('PERSON', 'ORGANIZATION', 'CULTURE_OR_UNKNOWN', name='creatortype', native_enum=False), nullable=False),
    sa.Column('nationality_culture', sa.String(length=255), nullable=True),
    sa.Column('date_start', sa.Integer(), nullable=True),
    sa.Column('date_end', sa.Integer(), nullable=True),
    sa.Column('place_start', sa.String(length=255), nullable=True),
    sa.Column('place_end', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('floor_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artworks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date_display', sa.String(length=255), nullable=False),
    sa.Column('date_start_year', sa.Integer(), nullable=True),
    sa.Column('date_end_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ON_VIEW', 'OFF_VIEW', name='artworkstatus', native_enum=False), nullable=False),
    sa.Column('medium', sa.String(length=500), nullable=True),
    sa.Column('accession_number', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artwork_creators',
    sa.Column('artwork_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('artwork_id', 'creator_id', 'role')
    )
    op.create_table('artwork_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artwork_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artwork_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('orb_descriptors', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_artworks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('artwork_id', sa.String(length=36), nullable=False),
    sa.Column('scan_order', sa.Integer(), nullable=False),
    sa.Column('photographed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_artworks')
    op.drop_table('reference_photos')
    op.drop_table('artwork_images')
    op.drop_table('artwork_creators')
    op.drop_table('artworks')
    op.drop_table('rooms')
    op.drop_table('visits')
    op.drop_table('floors')
    op.drop_table('creators')
    op.drop_table('categories')
    # ### end Alembic commands ###
